# Generated by Django 3.1.3 on 2020-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201125_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureName', models.CharField(max_length=30)),
                ('procedureDescription', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Competences',
            new_name='Competence',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='competencesName',
            new_name='competenceName',
        ),
    ]
