# Generated by Django 3.1.3 on 2020-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201126_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedureName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
