# Generated by Django 3.0.1 on 2020-11-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201127_1658'),
        ('portal', '0005_auto_20201127_1659'),
    ]

    operations = [
    ]
