# Generated by Django 3.1.3 on 2020-12-07 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_merge_20201128_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned'), ('Extra', 'Extra')], max_length=20)),
                ('factory_site', models.CharField(max_length=20)),
                ('factory_area', models.CharField(max_length=20)),
                ('activity_typology', models.CharField(choices=[('Electrical', 'Electrical'), ('Electronic', 'Electronic'), ('Hydraulic', 'Hydraulic'), ('Mechanical', 'Mechanical')], max_length=20)),
                ('activity_description', models.TextField()),
                ('estimation_time', models.PositiveIntegerField()),
                ('interruptible', models.BooleanField(default=False)),
                ('materials', models.TextField(blank=True, null=True)),
                ('week', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(1)])),
                ('workspace_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
