# Generated by Django 3.0.6 on 2020-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20201211_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='listProcedure',
            field=models.ManyToManyField(blank=True, null=True, to='portal.Procedure'),
        ),
    ]
