# Generated by Django 3.0.6 on 2020-12-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_competence_listprocedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='maintainer',
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='disponibilita',
            field=models.ManyToManyField(blank=True, null=True, to='portal.Availability'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Activity', unique=True)),
                ('maintainer', models.ForeignKey(limit_choices_to={'user_type': 'Maintainer'}, on_delete=django.db.models.deletion.CASCADE, to='portal.Profile')),
            ],
        ),
    ]
