# Generated by Django 3.1.3 on 2020-12-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_activity_competences_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='listProcedure',
        ),
        migrations.AddField(
            model_name='competence',
            name='listProcedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.procedure'),
        ),
    ]
