# Generated by Django 3.1.3 on 2020-12-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20201215_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='Assignment',
        ),
    ]
