# Generated by Django 3.0.6 on 2020-12-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20201215_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Maintainer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Profile'),
        ),
    ]
