# Generated by Django 3.0.6 on 2020-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201216_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assigned_to',
            field=models.BooleanField(default=False),
        ),
    ]
